name: core
description: core package
version: 0.0.6
author: xionghao
homepage: https://github.com/xionghaoo/flutter_core

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 本地文件夹目录
  path_provider: ^2.1.1
  # 网络请求
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/
